import MetaPixel from '@/lib/meta-pixel';
import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import './globals.css';

const Logo = '/logo.webp';

const geistSans = Lexend_Deca({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Advensa Travels',
    description: 'Generated by create next app',
    icons: {
        icon: Logo,
        apple: Logo,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} antialiased`}>
            <body className={`font-[family-name:var(--font-geist-sans)] bg-secondary/10`}>
                {children}
                <MetaPixel />
            </body>
        </html>
    );
}
