import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const Logo = '/logo.webp';

const geistSans = Poppins({
    variable: '--font-geist-sans',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Advensa Travels',
    description: 'Generated by create next app',
    icons: {
        icon: Logo,
        apple: Logo,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} antialiased`}>
            <body className={`font-[family-name:var(--font-geist-sans)] bg-secondary/10`}>
                {/* <Navbar /> */}
                {children}
            </body>
        </html>
    );
}
